### ISSUE TITLE
db is not being written on a mac.

### ISSUE THREAD

**Issue by ghost** [CyrisXD/Pwnagetty#3]
Running this on a mac, installed all dependencies via brew.

I'm a total noob at NodeJS, so I don't yet know the _why_, but I know that the script is creating a db.json file in my directory, but it is empty with length 0. I debugged, and concluded that the script was running perfectly up to the fs.writeFile.

I added some debug statements and confirmed that the 'db' variable was populated with a MAC address.

I confirmed that the JSON.stringify(db) command was indeed working properly.

I changed the fs.writeFile to a writeFileSync, and now the script works properly.

` console.log("Entering db Write");
        console.log(db);
        console.log(JSON.stringify(db));
        // Write data back to database
        fs.writeFileSync(config.database, JSON.stringify(db), (err) => {
            if(err) {
                console.log("Error writing file", err);
            }
            else {
                console.log("Updated database... \n \n")
                console.log("===================")
                console.log("   All done.  ")
                console.log("=================== \n")
                console.log("\n \n")
            }
        })`

The error or else statements aren't being printed, but the file is being written with the MAC address now.

i can finish this investigation, and submit a pull request, or you can look into it if you'd like.

**Comment by CyrisXD** [comment]
Hey bud you're welcome to improve on it where you can. I'm quite busy during this whole pandemic so I won't be able to test and debug but I'll be happy if you can test your side, make sure it's working and submit a pull request. 

Cheers
