### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by LonelyLuni** [CyrisXD/Pwnagetty#4]
i get this after i run it.. i have gotten results before.
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /home/luni/Pwnagetty/bin/index.js:73:29
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)

**Comment by HuggableShark** [comment]
I receive the same error. A workaround to dodge it I have noticed is to delete the db.json located in ~/Pwnagetty/bin/
This forces the program to remake the database each time, but I haven't seen any negative effects from this yet at least.
The `readDB` function on line 65 of Pwnagetty/bin/index.js seems to be where the error is emanating from.

**Comment by Cissoko420** [comment]
Was having same problem today, fixed it just by changing fs.writeFile to fs.writeFileSync (line 260) in index.js.
