### ISSUE TITLE
Command failed: hcxpcaptool

### ISSUE THREAD

**Issue by jeremyy44** [CyrisXD/Pwnagetty#6]
Hi I am trying to make pwnagetty work but I keep getting the same error every  time.
Main catch: Error: Command failed: hcxpcaptool -z ./pmkid/BELL480_a89a93fc3b76.pmkid ./pcap/BELL480_a89a93fc3b76.pcap
/bin/sh: 1: hcxpcaptool: not found
Is the error im getting
![Capture](https://user-images.githubusercontent.com/57967197/93030008-a60ac780-f5ed-11ea-8075-1318502dea94.PNG)

**Comment by CyrisXD** [comment]
Can you try pulling down the latest version? I merged a pull request this morning that replaced hcxpcaptool with hcxpcapngtool as the previous was deprecated.

**Comment by jeremyy44** [comment]
Well that fixed it for one command now i get this error
![Capture](https://user-images.githubusercontent.com/57967197/93030384-ab1d4600-f5f0-11ea-8026-801ff64f612d.PNG)

**Comment by CyrisXD** [comment]
I've just pushed another change, can you try pulling latest source now and try again? 
Apologies I don't have a Pwnagotchi or files to test with anymore so I'm doing this all blind. 

If that doesn't work, try deleting the db.json file and running the script then.

**Comment by jeremyy44** [comment]
no worry
pulling the latest source does seem to work with the old one deleting the db.json worked but only for one command now everything seem to be  working great

**Comment by CyrisXD** [comment]
Awesome 👍
