### ISSUE TITLE
HCCAPX and PMKID files have extra characters in front and at the end

### ISSUE THREAD

**Issue by felda** [CyrisXD/Pwnagetty#7]
Environment
OS: Kali running on WSL2 (Windows 10 Pro 2004)

When running the script it outputs the hccapx and pmkid files with junk data at the beginning and end.
Hashcat throws out `Hashfile './pmkid/NeatureIoT_b2935b6ed980.pmkid' on line 1 (WPA*01...3bb397*4e6561747572655f496f54***): Token length exception. ` The WPA*01 and *** at the end exist on every pmkid and hccapx file.

**Comment by cikeZ00** [comment]
I will assume you are still using the old deprecated 16800 format on hashcat.
Its now under the new 22000 hash mode.

` 22000 | WPA-PBKDF2-PMKID+EAPOL  `

try with `hashcat -m 22000`

**Comment by felda** [comment]
You are correct. I tried with 2500 and 16800 from the guides I saw floating around.

The 22000 did function normally. Thank you.
